orbs: # declare what orbs we are going to use
  node: circleci/node@4.1.0 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

# Define the jobs we want to run for this project
jobs:
  lint:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          command: npm run lint
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          command: npm run ci:test

  publish:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          command: npm run release:public

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - lint
      - test
      - publish:
        filters:
          branches:
            only:
              - master
