orbs: # declare what orbs we are going to use
  node: circleci/node@4.1.0 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

# Define the jobs we want to run for this project
jobs:
  lint:
    docker:
      - image: 'cimg/node:12'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  test:
    docker:
      - image: 'cimg/node:12'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - lint
      - test
